In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
import xgboost as xgb
from sklearn.metrics import mean_squared_error, accuracy_score, r2_score, mean_absolute_error
from sklearn import metrics

In [2]:
df=pd.read_csv('movie_metadata.csv')
# Reading the dataset

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
df
# loading the dataset

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force AwakensÂ ...,8,143,NaN,0.0,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,2283,Crystal Lowe,2.0,fraud|postal worker|prison|theft|trial,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,1753,Sam Underwood,1.0,cult|fbi|hideout|prison escape|serial killer,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,0,David Chandler,0.0,NaN,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,2386,Eliza Coupe,5.0,NaN,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,John August,My Date with Drew,4285,163,Jon Gunn,0.0,actress name in title|crush|date|four word tit...,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [5]:
df.shape
# the dataset has around 5043 rows and 28 columns

(5043, 28)

In [6]:
df.info()
# Checking the information on the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5031 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [7]:
df.isnull().sum()
# There are null values present in this dataset which have to be imputed.

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [8]:
df.columns
# Displaying all the column names present in the dataframe.

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [9]:
df['color'].value_counts()
# We have 4815 colour movies and 209 Black and white movies.

Color               4815
 Black and White     209
Name: color, dtype: int64

In [10]:
df.describe()
# Using the describe function to check the min, max values as well as mean and standard deviation.

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4993.000000,5028.000000,4939.000000,5020.000000,5036.000000,4.159000e+03,5.043000e+03,5043.000000,5030.000000,5022.000000,4.551000e+03,4935.000000,5030.000000,5043.000000,4714.000000,5043.000000
mean,140.194272,107.201074,686.509212,645.009761,6560.047061,4.846841e+07,8.366816e+04,9699.063851,1.371173,272.770808,3.975262e+07,2002.470517,1651.754473,6.442138,2.220403,7525.964505
std,121.601675,25.197441,2813.328607,1665.041728,15020.759120,6.845299e+07,1.384853e+05,18163.799124,2.013576,377.982886,2.061149e+08,12.474599,4042.438863,1.125116,1.385113,19320.445110
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,50.000000,93.000000,7.000000,133.000000,614.000000,5.340988e+06,8.593500e+03,1411.000000,0.000000,65.000000,6.000000e+06,1999.000000,281.000000,5.800000,1.850000,0.000000
50%,110.000000,103.000000,49.000000,371.500000,988.000000,2.551750e+07,3.435900e+04,3090.000000,1.000000,156.000000,2.000000e+07,2005.000000,595.000000,6.600000,2.350000,166.000000
75%,195.000000,118.000000,194.500000,636.000000,11000.000000,6.230944e+07,9.630900e+04,13756.500000,2.000000,326.000000,4.500000e+07,2011.000000,918.000000,7.200000,2.350000,3000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,1.221550e+10,2016.000000,137000.000000,9.500000,16.000000,349000.000000

In [11]:
df.nunique()
# Displays the total number of variables present in the data frames columns

color                           2
director_name                2398
num_critic_for_reviews        528
duration                      191
director_facebook_likes       435
actor_3_facebook_likes        906
actor_2_name                 3032
actor_1_facebook_likes        878
gross                        4035
genres                        914
actor_1_name                 2097
movie_title                  4917
num_voted_users              4826
cast_total_facebook_likes    3978
actor_3_name                 3521
facenumber_in_poster           19
plot_keywords                4760
movie_imdb_link              4919
num_user_for_reviews          954
language                       47
country                        65
content_rating                 18
budget                        439
title_year                     91
actor_2_facebook_likes        917
imdb_score                     78
aspect_ratio                   22
movie_facebook_likes          876
dtype: int64

In [12]:
df['language'].value_counts()
# A lot of movies in this dataset are in English.

English       4704
French          73
Spanish         40
Hindi           28
Mandarin        26
German          19
Japanese        18
Cantonese       11
Russian         11
Italian         11
Portuguese       8
Korean           8
Arabic           5
Danish           5
Hebrew           5
Swedish          5
Polish           4
Norwegian        4
Persian          4
Dutch            4
Thai             3
Chinese          3
Icelandic        2
None             2
Indonesian       2
Aboriginal       2
Romanian         2
Dari             2
Zulu             2
Panjabi          1
Urdu             1
Vietnamese       1
Slovenian        1
Greek            1
Dzongkha         1
Tamil            1
Telugu           1
Kannada          1
Czech            1
Hungarian        1
Bosnian          1
Filipino         1
Mongolian        1
Maya             1
Aramaic          1
Kazakh           1
Swahili          1
Name: language, dtype: int64

In [13]:
df['movie_title']
# Displaying all the movie names.

0                                                 AvatarÂ
1               Pirates of the Caribbean: At World's EndÂ
2                                                SpectreÂ
3                                  The Dark Knight RisesÂ
4       Star Wars: Episode VII - The Force AwakensÂ    ...
                              ...
5038                             Signed Sealed DeliveredÂ
5039                           The FollowingÂ
5040                                A Plague So PleasantÂ
5041                                    Shanghai CallingÂ
5042                                   My Date with DrewÂ
Name: movie_title, Length: 5043, dtype: object

In [14]:
df.movie_title[df.language == 'Hindi']
# printing the name of Hindi movies present in the dataset.

1056                                 EarthÂ
3075                Kabhi Alvida Naa KehnaÂ
3085                             HousefullÂ
3208                                KrrishÂ
3276                      Jab Tak Hai JaanÂ
3344                       My Name Is KhanÂ
3348                       Namastey LondonÂ
3350               Yeh Jawaani Hai DeewaniÂ
3455                         Ta Ra Rum PumÂ
3510                            Veer-ZaaraÂ
3665                           Khiladi 786Â
3685                       Rang De BasantiÂ
3695                         Dum Maaro DumÂ
3789                     Gandhi, My FatherÂ
3866                                 FuglyÂ
3870                               AirliftÂ
3877                                   PaaÂ
4088                                 WaterÂ
4160                  Lage Raho Munna BhaiÂ
4299                Hum To Mohabbat KaregaÂ
4305                        Roadside RomeoÂ
4351             ABCD (Any Body Can Dance)Â
4385                          The LunchboxÂ
4490                       Monsoon WeddingÂ
4528    Rocket Singh: Salesman of the YearÂ
4572                                  FizaÂ
4593          Chocolate: Deep Dark SecretsÂ
4724                     Faith ConnectionsÂ
Name: movie_title, dtype: object

In [15]:
bw=df[df.language == 'Hindi']
# Saving the Hindi movies into a separate dataframe for futher analysis

In [16]:
bw
# Dataframe of all hindi movies with high imdb scores

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
1056,Color,Deepa Mehta,34.0,110.0,375.0,59.0,Gulshan Grover,113.0,528972.0,Drama|Romance|War,Nandita Das,Earth,5639,371,Eric Peterson,0.0,friend|hindu|india|muslim|sikh,http://www.imdb.com/title/tt0150433/?ref_=fn_t...,55.0,Hindi,India,Unrated,NaN,1998.0,102.0,7.8,NaN,522
3075,Color,Karan Johar,20.0,193.0,160.0,860.0,John Abraham,8000.0,3275443.0,Drama,Shah Rukh Khan,Kabhi Alvida Naa Kehna,13998,10822,Preity Zinta,2.0,extramarital affair|fashion magazine editor|ma...,http://www.imdb.com/title/tt0449999/?ref_=fn_t...,264.0,Hindi,India,R,700000000.0,2006.0,1000.0,6.0,2.35,659
3085,Color,Sajid Khan,10.0,144.0,0.0,119.0,Boman Irani,564.0,1165104.0,Comedy,Arjun Rampal,Housefull,8598,1121,Riteish Deshmukh,5.0,bad luck|casino|lie|mix up|stutter,http://www.imdb.com/title/tt1573072/?ref_=fn_t...,43.0,Hindi,India,NaN,NaN,2010.0,154.0,5.3,NaN,250
3208,Color,Rakesh Roshan,20.0,168.0,53.0,45.0,Rekha,307.0,NaN,Action|Adventure|Romance|Sci-Fi,Naseeruddin Shah,Krrish,12411,616,Sharat Saxena,0.0,breaking the fourth wall|breaking the fourth w...,http://www.imdb.com/title/tt0432637/?ref_=fn_t...,110.0,Hindi,India,Not Rated,10000000.0,2006.0,200.0,6.3,2.35,533
3276,Color,Yash Chopra,50.0,176.0,147.0,1000.0,Katrina Kaif,8000.0,3047539.0,Drama|Romance,Shah Rukh Khan,Jab Tak Hai Jaan,42296,13762,Vic Waghorn,4.0,accident|army|bomb|indian army|love,http://www.imdb.com/title/tt2176013/?ref_=fn_t...,286.0,Hindi,India,Not Rated,7217600.0,2012.0,3000.0,6.9,2.35,12000
3344,Color,Karan Johar,210.0,128.0,160.0,81.0,Jimmy Shergill,8000.0,4018695.0,Adventure|Drama|Thriller,Shah Rukh Khan,My Name Is Khan,69759,8532,Christopher B. Duncan,2.0,airport|asperger's syndrome|autism|muslim|raci...,http://www.imdb.com/title/tt1188996/?ref_=fn_t...,235.0,Hindi,India,PG-13,12000000.0,2010.0,327.0,8.0,2.35,27000
3348,Color,Vipul Amrutlal Shah,15.0,128.0,11.0,119.0,Clive Standen,3000.0,1207007.0,Comedy|Drama|Romance,Katrina Kaif,Namastey London,13577,4004,Riteish Deshmukh,2.0,india|london england|marriage|stereotype|sugar...,http://www.imdb.com/title/tt0795434/?ref_=fn_t...,47.0,Hindi,India,NaN,NaN,2007.0,687.0,7.3,NaN,341
3350,Color,Ayan Mukerji,25.0,160.0,0.0,417.0,Madhuri Dixit,964.0,3827466.0,Comedy|Drama|Musical|Romance,Ranbir Kapoor,Yeh Jawaani Hai Deewani,25122,2350,Aditya Roy Kapoor,2.0,jealousy|jumping into sea|love|swimming pool|w...,http://www.imdb.com/title/tt2178470/?ref_=fn_t...,102.0,Hindi,India,Not Rated,NaN,2013.0,551.0,6.9,NaN,0
3455,Color,Siddharth Anand,16.0,153.0,5.0,60.0,Mary Goggin,532.0,872643.0,Comedy|Family|Romance,Saif Ali Khan,Ta Ra Rum Pum,2909,902,Vic Aviles,3.0,comeback|family relationships|marriage|new yor...,http://www.imdb.com/title/tt0833553/?ref_=fn_t...,37.0,Hindi,USA,NaN,6000000.0,2007.0,249.0,5.4,NaN,108
3510,Color,Yash Chopra,29.0,192.0,147.0,397.0,Preity Zinta,8000.0,2921738.0,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,9984,Anupam Kher,0.0,fair|pakistan|prison|rescue|stranded,http://www.imdb.com/title/tt0420332/?ref_=fn_t...,119.0,Hindi,India,NaN,7000000.0,2004.0,860.0,7.9,2.35,2000
3665,Color,Ashish R. Mohan,23.0,141.0,2.0,61.0,Mithun Chakraborty,634.0,352684.0,Action|Comedy,Asin,Khiladi 786,4633,1065,Johnny Lever,1.0,car crash|impersonating a police officer|long ...,http://www.imdb.com/title/tt2166214/?ref_=fn_t...,31.0,Hindi,India,Not Rated,NaN,2012.0,284.0,4.3,NaN,365
3685,Color,Rakeysh Omprakash Mehra,33.0,157.0,85.0,199.0,Steven Mackintosh,397.0,2197331.0,Comedy|Drama|History|Romance,Anupam Kher,Rang De Basanti,70233,1519,Madhavan,0.0,freedom|friend|india|student|urination,http://www.imdb.com/title/tt0405508/?ref_=fn_t...,321.0,Hindi,India,Not Rated,NaN,2006.0,227.0,8.4,2.35,0
3695,Color,Rohan Sippy,24.0,128.0,4.0,47.0,Bipasha Basu,374.0,563699.0,Action|Crime|Drama|Thriller,Abhishek Bachchan,Dum Maaro Dum,3266,787,Prateik,0.0,airport|drugs|loss of loved one|police|title b...,http://www.imdb.com/title/tt1618430/?ref_=fn_t...,27.0,Hindi,India,R,NaN,2011.0,282.0,6.2,NaN,421
3789,Color,Feroz Abbas Khan,16.0,136.0,0.0,14.0,Bhoomika Chawla,75.0,240425.0,Biography|Drama|History,Akshaye Khanna,"Gandhi, My Father",1311,172,Darshan Jariwala,0.0,africa|hindu|india|muslim|south africa,http://www.imdb.com/title/tt0459293/?ref_=fn_t...,25.0,Hindi,India,NaN,NaN,2007.0,45.0,7.4,2.35,133
3866,Color,Kabir Sadanand,9.0,134.0,0.0,62.0,Sana Saeed,327.0,NaN,Drama|Thriller,Jimmy Shergill,Fugly,781,496,Dimple Kapadia,4.0,NaN,http://www.imdb.com/title/tt3683702/?ref_=fn_t...,7.0,Hindi,India,NaN,NaN,2014.0,82.0,4.7,NaN,62
3870,Color,Raja Menon,39.0,130.0,6.0,12.0,Sameer Ali Khan,85.0,NaN,Action|Drama|History|Thriller|War,Nimrat Kaur,Airlift,30977,151,Purab Kohli,1.0,1990s|businessman|evacuation|historical fictio...,http://www.imdb.com/title/tt4387040/?ref_=fn_t...,178.0,Hindi,India,NaN,4400000.0,2016.0,26.0,8.5,2.35,10000
3877,Color,R. Balki,12.0,133.0,12.0,106.0,Abhishek Bachchan,464.0,199228.0,Comedy|Drama,Vidya Balan,Paa,7295,1045,Paresh Rawal,0.0,adult actor playing minor|politician|progeria|...,http://www.imdb.com/title/tt1532957/?ref_=fn_t...,49.0,Hindi,India,NaN,150000000.0,2009.0,374.0,7.2,2.35,504
4088,Color,Deepa Mehta,91.0,117.0,375.0,31.0,Lisa Ray,1000.0,3222857.0,Drama|Romance,John Abraham,Water,12560,1394,Seema Biswas,0.0,ashram|india|love|tradition|widow,http://www.imdb.com/title/tt0240200/?ref_=fn_t...,147.0,Hindi,Canada,PG-13,NaN,2005.0,329.0,7.8,2.35,0
4160,Color,Rajkumar Hirani,15.0,144.0,124.0,327.0,Sanjay Dutt,464.0,NaN,Comedy|Drama|Romance,Vidya Balan,Lage Raho Munna Bhai,27569,1761,Jimmy Shergill,0.0,love|professor of history|radio|satyagraha|uns...,http://www.imdb.com/title/tt0456144/?ref_=fn_t...,106.0,Hindi,India,PG-13,120000000.0,2006.0,426.0,8.2,2.35,349
4299,Color,Kundan Shah,1.0,NaN,4.0,72.0,Bobby Deol,353.0,NaN,Action|Comedy|Romance|Thriller,Karisma Kapoor,Hum To Mohabbat Karega,275,613,Shakti Kapoor,2.0,elevator|news reporter|police|restaurant|waiter,http://www.imdb.com/title/tt0249588/?ref_=fn_t...,1.0,Hindi,India,NaN,NaN,2000.0,89.0,2.8,NaN,10
4305,Color,Jugal Hansraj,6.0,93.0,32.0,24.0,Sanjay Mishra,532.0,55202.0,Animation|Comedy|Family|Romance,Saif Ali Khan,Roadside Romeo,922,653,Javed Jaffrey,0.0,india|love|love at first sight|mumbai india|re...,http://www.imdb.com/title/tt1050739/?ref_=fn_t...,17.0,Hindi,India,PG,NaN,2008.0,85.0,5.3,2.35,39
4351,Color,Remo,15.0,160.0,168.0,71.0,Remo,733.0,95236.0,Drama|Musical,Lauren Gottlieb,ABCD (Any Body Can Dance),5018,1182,Prabhudheva,3.0,NaN,http://www.imdb.com/title/tt2321163/?ref_=fn_t...,38.0,Hindi,India,Not Rated,NaN,2013.0,168.0,6.4,NaN,1000
4385,Color,Ritesh Batra,195.0,104.0,25.0,73.0,Nimrat Kaur,638.0,4231500.0,Drama|Romance,Nawazuddin Siddiqui,The Lunchbox,30479,822,Lillete Dubey,2.0,delivery|delivery to wrong address|lunchbox|op...,http://www.imdb.com/title/tt2350496/?ref_=fn_t...,162.0,Hindi,India,PG,1000000.0,2013.0,85.0,7.8,2.35,16000
4490,Color,Mira Nair,137.0,114.0,300.0,73.0,Randeep Hooda,307.0,13876974.0,Comedy|Drama|Romance,Naseeruddin Shah,Monsoon Wedding,19397,809,Lillete Dubey,0.0,arranged marriage|bride|celebration|marriage|w...,http://www.imdb.com/title/tt0265343/?ref_=fn_t...,214.0,Hindi,India,R,7000000.0,2001.0,209.0,7.4,1.85,0
4528,Color,Shimit Amin,14.0,150.0,6.0,20.0,Shazahn Padamsee,964.0,NaN,Comedy|Drama,Ranbir Kapoor,Rocket Singh: Salesman of the Year,11010,1052,Gauhar Khan,1.0,boss|computer|honesty|sales|salesman,http://www.imdb.com/title/tt1434447/?ref_=fn_t...,35.0,Hindi,India,NaN,NaN,2009.0,22.0,7.5,NaN,773
4572,Black and White,Khalid Mohamed,1.0,167.0,10.0,97.0,Manoj Bajpayee,353.0,610991.0,Drama|Romance,Karisma Kapoor,Fiza,2715,773,Jaya Bhaduri,3.0,mumbai riots|politician|riot|suicide|tragic event,http://www.imdb.com/title/tt0248012/?ref_=fn_t...,19.0,Hindi,India,NaN,1000000.0,2000.0,186.0,6.2,2.35,92
4593,Color,Vivek Agnihotri,4.0,160.0,5.0,219.0,Anil Kapoor,724.0,49000.0,Thriller,Emraan Hashmi,Chocolate: Deep Dark Secrets,1524,2024,Sunil Shetty,5.0,chocolate|christmas|christmas eve|death|suspect,http://www.imdb.com/title/tt0454431/?ref_=fn_t...,30.0,Hindi,India,NaN,1500000.0,2005.0,668.0,4.8,NaN,31
4724,Color,Pan Nalin,19.0,115.0,95.0,0.0,Pant Shirt Baba,0.0,NaN,Biography|Documentary|Drama,Bhole Baba,Faith Connections,113,0,Shriman Umeshanad Brahmachari,1.0,faith|ganja|kumbh mela|little boy|orphan,http://www.imdb.com/title/tt2768766/?ref_=fn_t...,3.0,Hindi,India,NaN,550000.0,2013.0,0.0,7.0,1.85,126

In [17]:
scores=bw.imdb_score[bw.imdb_score>=7]
# storing movies with imdb score equal to 8 or above 8

In [18]:
name=bw.movie_title[bw.imdb_score>=7]
# storing movie_titles with imdb scores above 8 or equal to 8

In [19]:
genre=bw.genres[bw.imdb_score>=7]
# storing movie genre with imdb score above or equal to 8

In [20]:
bollywoodmovieratings=pd.concat([name,genre,scores],axis=1)
# creating a dataframe with all values concatenated into one dataframe

In [21]:
bollywoodmovieratings
# final concatenated dataframe of Indian movies and their genres and imdb_scores

,movie_title,genres,imdb_score
1056,Earth,Drama|Romance|War,7.8
3344,My Name Is Khan,Adventure|Drama|Thriller,8.0
3348,Namastey London,Comedy|Drama|Romance,7.3
3510,Veer-Zaara,Drama|Musical|Romance,7.9
3685,Rang De Basanti,Comedy|Drama|History|Romance,8.4
3789,"Gandhi, My Father",Biography|Drama|History,7.4
3870,Airlift,Action|Drama|History|Thriller|War,8.5
3877,Paa,Comedy|Drama,7.2
4088,Water,Drama|Romance,7.8
4160,Lage Raho Munna Bhai,Comedy|Drama|Romance,8.2
4385,The Lunchbox,Drama|Romance,7.8
4490,Monsoon Wedding,Comedy|Drama|Romance,7.4
4528,Rocket Singh: Salesman of the Year,Comedy|Drama,7.5
4724,Faith Connections,Biography|Documentary|Drama,7.0

#### As seen above Indian movies have a higher imdb score if it has a genre with Action|Drama|History|Thriller|War included in it.

## Data visualization

In [ ]:
sns.pairplot(data=df)

In [ ]:
f,ax=plt.subplots(figsize=(10,20)) 
ax1=plt.subplot(211)
f.suptitle("Imdb score distribution")
explode=(0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05)
df['imdb_score'].value_counts(ascending=False).head(10).plot('pie',autopct="%0.2f%%",explode=explode,ax=ax1)
# Pie plot for top 10 Imdb_scores.
# Around 11.74 percent of the data has a imdb_score which is 6.7

In [ ]:
# Distribution plot for all prices.
f,ax=plt.subplots(figsize=(30,10))
ax3=plt.subplot(224)
sns.distplot(df['imdb_score'],ax=ax3)
# Using the distribution plot we can see that the imdb score is the highest at a imdb score which is between 6 and 8

In [ ]:
sns.set_style("darkgrid")
ls=df['language'].value_counts().head(15).sort_values(ascending=False)
plt.figure(figsize=(15,8))
temp =sns.barplot(ls.index, ls.values, alpha=0.8)
plt.ylabel('COUNT', fontsize=14)
plt.xlabel('Type of Languages', fontsize=28)
temp.set_xticklabels(rotation=90,labels=ls.index,fontsize=15)
plt.show()
# Visualizing the count of languages in the dataset.

In [ ]:
sns.set_style("darkgrid")
ls=df['director_name'].value_counts().head(20).sort_values(ascending=False)
plt.figure(figsize=(15,8))
temp =sns.barplot(ls.index, ls.values, alpha=0.8)
plt.ylabel('COUNT', fontsize=14)
plt.xlabel('Name of Director', fontsize=28)
temp.set_xticklabels(rotation=90,labels=ls.index,fontsize=15)
plt.show()
# Visualizing the Directors names present in the dataset.

In [ ]:
plt.figure(figsize=(20, 6))
sns.barplot(x='country',y='imdb_score',data=df);
plt.xticks(rotation=90)
# Visualizing the barplot of countries and the imdb scores.

In [ ]:
plt.figure(figsize=(20, 6))
sns.barplot(x='content_rating',y='imdb_score',hue='color',data=df);
plt.xticks(rotation=90)
# This visualization shows the type of content having higher imdbscore and shows us the type of movie color present in data

In [ ]:
plt.figure(figsize=(20, 6))
sns.barplot(x='content_rating',y='aspect_ratio',hue='color',data=df);
plt.xticks(rotation=90)
# This visualization shows the type of content rating on X-axis having aspect ratio on Y-axis and hue with type of movie color.

In [ ]:
plt.figure(figsize=(20, 6))
sns.barplot(x='aspect_ratio',y='imdb_score',hue='color',data=df);
plt.xticks(rotation=90)
# This visualization shows the aspect ratio and its imdb score with hue as the color column.

In [ ]:
df=df.dropna()
# Removing null values

In [ ]:
df.isnull().sum()
# As you can see there is no null values present in the dataset now.

In [ ]:
df.columns

In [ ]:
df=df.drop(columns=['movie_imdb_link','color','movie_title','facenumber_in_poster', 'plot_keywords',
                    'actor_3_name','movie_imdb_link','aspect_ratio','language'])

In [ ]:
df

In [ ]:
df.shape
# The number of columns have now been reduced to 20

## Label Encoding Categorical data

In [ ]:
cat_cols=['content_rating','director_name','genres','actor_1_name','actor_2_name','country']
le=LabelEncoder()
for i in cat_cols:
    df[i]=le.fit_transform(df[i])
df.dtypes
## We have label encoded the categorical columns in the dataset and transformed them to numeric values.

# Distribution Plot

In [ ]:
rows=4
cols=5
fig, ax=plt.subplots(nrows=rows,ncols=cols,figsize=(20,20))
col=df.columns
index=0
for i in range(rows):
    for j in range(cols):
        sns.distplot(df[col[index]],ax=ax[i][j])
        index=index+1
        
plt.tight_layout()
# The distribution plot shows us the overall distribution of the data.

# Log Transformation

In [ ]:
df.columns                       
# Displaying all column names,copypaste this in the next cell.

In [ ]:
skewed_features=['director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'num_voted_users', 'cast_total_facebook_likes', 'num_user_for_reviews',
       'country', 'content_rating', 'budget', 'title_year',
       'actor_2_facebook_likes', 'imdb_score', 'movie_facebook_likes']
# Selecting all features which are skewed and storing them i n the skewed_features

In [ ]:
for i in skewed_features:
    df[i]=np.log(df[i]+1)
# Applying log transformation on the skewed features

In [ ]:
rows=4
cols=5
fig, ax=plt.subplots(nrows=rows,ncols=cols,figsize=(20,20))
col=df.columns
index=0
for i in range(rows):
    for j in range(cols):
        sns.distplot(df[col[index]],ax=ax[i][j])
        index=index+1
        
plt.show()
# Checking the changes in the distribution of data after applying log transformation.

## Splitting dataset

In [ ]:
X=df.drop(labels=['imdb_score'],axis=1)
Y=df['imdb_score']
X.head()
# splitting data into dependent and independent variables

In [ ]:
Y.head()
# target column

In [ ]:
# Train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=40)
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)
# Splitting data set into training and testing.

# Machine Learning

### Linear Regression

In [ ]:
lm=LinearRegression()   
lm = lm.fit(X_train,Y_train)

#Traindata Predictions
train_pred = lm.predict(X_train)

#testdata predictions
test_pred = lm.predict(X_test)


RMSE_test = np.sqrt(mean_squared_error(Y_test, test_pred))
RMSE_train= np.sqrt(mean_squared_error(Y_train,train_pred))
print("RMSE TrainingData = ",str(RMSE_train))
print("RMSE TestData = ",str(RMSE_test))
print('-'*50)
print('RSquared value on train:',lm.score(X_train, Y_train))
print('RSquared value on test:',lm.score(X_test, Y_test))

In [ ]:
errors = abs(test_pred - Y_test)
# Calculating errors for using error values in mean absolute percentage error

In [ ]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / Y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

### Decision Tree Regressor

In [ ]:
DT=DecisionTreeRegressor(max_depth=9)
DT.fit(X_train,Y_train)

#predicting train
train_preds=DT.predict(X_train)
#predicting on test
test_preds=DT.predict(X_test)

RMSE_train=(np.sqrt(metrics.mean_squared_error(Y_train,train_preds)))
RMSE_test=(np.sqrt(metrics.mean_squared_error(Y_test,test_preds)))
print("RMSE TrainingData = ",str(RMSE_train))
print("RMSE TestData = ",str(RMSE_test))
print('-'*50)
print('RSquared value on train:',DT.score(X_train, Y_train))
print('RSquared value on test:',DT.score(X_test, Y_test))

In [ ]:
errors = abs(test_preds - Y_test)
# Calculating errors for using error values in mean absolute percentage error

In [ ]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / Y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

### Random Forest Regressor

In [ ]:
RF=RandomForestRegressor().fit(X_train,Y_train)

#predicting train
train_preds1=RF.predict(X_train)
#predicting on test
test_preds1=RF.predict(X_test)

RMSE_train=(np.sqrt(metrics.mean_squared_error(Y_train,train_preds1)))
RMSE_test=(np.sqrt(metrics.mean_squared_error(Y_test,test_preds1)))
print("RMSE TrainingData = ",str(RMSE_train))
print("RMSE TestData = ",str(RMSE_test))
print('-'*50)
print('RSquared value on train:',RF.score(X_train, Y_train))
print('RSquared value on test:',RF.score(X_test, Y_test))

In [ ]:
errors = abs(test_preds1 - Y_test)
# Calculating errors for using error values in mean absolute percentage error

In [ ]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / Y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

### K-Nearest Neighbours

In [ ]:
knn=KNeighborsRegressor()
knn.fit(X_train,Y_train)

#predicting train
train_preds2=knn.predict(X_train)
#predicting on test
test_preds2=knn.predict(X_test)

RMSE_train=(np.sqrt(metrics.mean_squared_error(Y_train,train_preds2)))
RMSE_test=(np.sqrt(metrics.mean_squared_error(Y_test,test_preds2)))
print("RMSE TrainingData = ",str(RMSE_train))
print("RMSE TestData = ",str(RMSE_test))
print('-'*50)
print('RSquared value on train:',knn.score(X_train, Y_train))
print('RSquared value on test:',knn.score(X_test, Y_test))

In [ ]:
# More machine learning algorithms.

In [ ]:
from sklearn.linear_model import LassoCV
from sklearn.linear_model import RidgeCV
from sklearn.linear_model import ElasticNetCV
from sklearn.ensemble import GradientBoostingRegressor

### Lasso Regression

In [ ]:
lasso = LassoCV(cv=10).fit(X_train, Y_train)


#predicting train
train_preds3=lasso.predict(X_train)
#predicting on test
test_preds3=lasso.predict(X_test)

RMSE_train=(np.sqrt(metrics.mean_squared_error(Y_train,train_preds3)))
RMSE_test=(np.sqrt(metrics.mean_squared_error(Y_test,test_preds3)))
print("RMSE TrainingData = ",str(RMSE_train))
print("RMSE TestData = ",str(RMSE_test))
print('-'*50)
print('RSquared value on train:',lasso.score(X_train, Y_train))
print('RSquared value on test:',lasso.score(X_test, Y_test))

### Ridge Regression

In [ ]:
ridge = RidgeCV(cv=10).fit(X_train, Y_train)
#predicting train
train_preds4=ridge.predict(X_train)
#predicting on test
test_preds4=ridge.predict(X_test)

RMSE_train=(np.sqrt(metrics.mean_squared_error(Y_train,train_preds4)))
RMSE_test=(np.sqrt(metrics.mean_squared_error(Y_test,test_preds4)))
print("RMSE TrainingData = ",str(RMSE_train))
print("RMSE TestData = ",str(RMSE_test))
print('-'*50)
print('RSquared value on train:',ridge.score(X_train, Y_train))
print('RSquared value on test:',ridge.score(X_test, Y_test))

### Elastic Net

In [ ]:
elastic_net = ElasticNetCV(cv = 10).fit(X_train, Y_train)
#predicting train
train_preds5=elastic_net.predict(X_train)
#predicting on test
test_preds5=elastic_net.predict(X_test)

RMSE_train=(np.sqrt(metrics.mean_squared_error(Y_train,train_preds5)))
RMSE_test=(np.sqrt(metrics.mean_squared_error(Y_test,test_preds5)))
print("RMSE TrainingData = ",str(RMSE_train))
print("RMSE TestData = ",str(RMSE_test))
print('-'*50)
print('RSquared value on train:',elastic_net.score(X_train, Y_train))
print('RSquared value on test:',elastic_net.score(X_test, Y_test))

### XG-Boost Regressor

In [ ]:
xgbr =xgb.XGBRegressor().fit(X_train, Y_train)
#predicting train
train_preds6=xgbr.predict(X_train)
#predicting on test
test_preds6=xgbr.predict(X_test)

RMSE_train=(np.sqrt(metrics.mean_squared_error(Y_train,train_preds6)))
RMSE_test=(np.sqrt(metrics.mean_squared_error(Y_test,test_preds6)))
print("RMSE TrainingData = ",str(RMSE_train))
print("RMSE TestData = ",str(RMSE_test))
print('-'*50)
print('RSquared value on train:',xgbr.score(X_train, Y_train))
print('RSquared value on test:',xgbr.score(X_test, Y_test))

In [ ]:
errors = abs(test_preds6 - Y_test)
# Calculating errors for using error values in mean absolute percentage error

In [ ]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / Y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

In [ ]:
# Before log transformation the xg boost Accuracy was 91.87 % and now accuracy has improved to 96.49 percent.